---
functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен соответствовать требованиям надежности и безопасности веб-сайтов
  - Провести кроссбраузерное тестирование 
  - Проверить как отображается сайт на различных мобильных устройствах
  - Добавить подробное описание товаров 
  - Проверить адаптивность верстки сайта
  - Проверить скорость загрузки сайта
